default_value: &default
  source_type: ["bank", "westpac", "xeroapi"]
  payment_type: ["bank"]
  log_level: DEBUG
  archive_limit: 7
  search_day_diff: 3
  member_whitelist: ["1", "2"]
  resend_frequence: 10
  resend_lag: 60
  rails_env: "development"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

fiat:
  <<: *default

bank:
  <<: *default