default_value: &default
  payment_type: ["bank"]
  log_level: DEBUG
  archive_limit: 7
  search_day_diff: 3
  member_whitelist: ["1", "2"]

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

fiat:
  <<: *default