fiat: &default
  payment_type: ["bank"]
  log_level: DEBUG
  archive_limit: 7
  search_day_diff: 3
  member_whitelist: ["1", "2"]
  resend_frequence: 10
  resend_lag: 60
  rails_env: "development"

bank:
  <<: *default

westpac:
  bank_account_regex: \d{12}|\d{14}
  import_filter_categories: ["DEP", "CREDIT", "ATM", "OTHER", "DEBIT", "FEE"]